spring:
  datasource:
    url: jdbc:mysql://rm-wz9326kafub0mvn0uyo.mysql.rds.aliyuncs.com/artanbao-ar?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: Root@2019
  redis:
    database: 0
    host: 47.95.148.150
    port: 6379
    password: ar12345
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000
server:
  port: 8686
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:
